name: site_mateus
description: A new Flutter project.


publish_to: 'none' 





version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0


  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  
  assets:
    - assets/images/  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
